FROM openjdk:17

WORKDIR /usr/src/myapp

COPY . /usr/src/myapp/

#ENV SPRING_DATASOURCE_USERNAME=vaishnav
#ENV SPRING_DATASOURCE_PASSWORD=vaishnav

CMD [ "java","-jar","DockerTest-0.0.1-SNAPSHOT.jar" ]

EXPOSE 8081